version: '3.7'
services:
  web:
    image: nginx:1.17.9-alpine
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ${NGINX_CONFIG}:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    links:
      - app
    working_dir: ${APP_PATH_CONTAINER}
  app:
    image: php:7.4.4-fpm-alpine
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}