version: '3.7'
services:
  web:
    image: nginx:1.17.9-alpine
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ${NGINX_CONFIG}:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    links:
      - app
    working_dir: ${APP_PATH_CONTAINER}
  app:
    build: ./app
    container_name: financier_app
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    user: www-data
    links:
      - database
  database:
    image: mysql/mysql-server:8.0.19-1.1.15
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=financier"
    ports:
      - "33061:3306"
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql