version: '3.7'
services:
  web:
    image: nginx:1.17.9-alpine
    container_name: financier_web
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ${PHPMYADMIN_PATH}:${PHPMYADMIN_PATH_CONTAINER}
      - ${NGINX_CONFIG}:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    links:
      - app
      - phpmyadmin
    working_dir: ${APP_PATH_CONTAINER}
  app:
    build: ./app
    container_name: financier_app
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    user: www-data
    links:
      - database
  database:
    image: mysql:8.0.19
    container_name: financier_db
    environment:
      - ${MYSQL_DATABASE}
      - ${MYSQL_ROOT_PASSWORD}
      - ${MYSQL_USER}
      - ${MYSQL_PASSWORD}
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql
      - ${DB_CONFIG}:/etc/mysql/conf.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:fpm-alpine
    container_name: financier_pma
    volumes:
      - ${PHPMYADMIN_PATH}:${PHPMYADMIN_PATH_CONTAINER}
    working_dir: ${PHPMYADMIN_PATH_CONTAINER}
    links:
      - database:db
  composer:
    image: composer:latest
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    command: composer install --ignore-platform-reqs